export enum FermentableAction {
  ADD = 'FERMENTABLE/ADD',
  REMOVE = 'FERMENTABLE/REMOVE',
  SET_GRAVITY = 'FERMENTABLE/SET_GRAVITY',
  SET_LOVIBOND = 'FERMENTABLE/SET_LOVIBOND',
  SET_QUANTITY = 'FERMENTABLE/SET_QUANTITY',
  SET_WEIGHT = 'FERMENTABLE/SET_WEIGHT',
}
