export enum AppRoute {
  RECIPE_BUILDER = 'RECIPE_BUILDER',
  RECIPE_CARD = 'RECIPE_CARD',
  ROOT_MENU = 'ROOT_MENU',
}

export enum BuilderRoutes {
  FERMENTABLES = 'FERMENTABLES',
  HOPS = 'HOPS',
  MASH = 'MASH',
  FERMENTATION = 'FERMENTATION',
  STYLE = 'STYLE',
}
